LIST

In [ ]:
#Task 1

list1 = []

while True:
  user = input()
  if user == "STOP":
    break
  else:
    list1.append(int(user))

print()

for i in range(len(list1)):
  if list1[i] not in list1[:i]:
    counter = 1
    for j in range(i+1,len(list1)):
      if list1[i] == list1[j]:
        counter += 1
    print(list1[i],"-",counter,"times")

10
20
20
30
10
50
90
STOP

10 - 2 times
20 - 2 times
30 - 1 times
50 - 1 times
90 - 1 times

In [ ]:
#Task 1 (Class)
uniq_list = []
freq_list = []
all_list = []

while True:
    user = input()
    if user == "STOP":
        break
    else:
        all_list.append(int(user))
        if int(user) not in uniq_list:
            uniq_list.append(int(user))

for i in uniq_list:
    counter = 0
    for j in all_list:
        if j == i:
            counter += 1
    freq_list.append(counter)

for k in range(len(freq_list)):
    print(uniq_list[k],"-",freq_list[k],"times")

In [ ]:
#Task 2
N = int(input("Type the value of N: "))
lists = []
sum = 0
sum_list = []

for i in range(N):
    user_input = input("Enter the list values separated by space: ")
    current_list = [int(val) for val in user_input.split()]
    lists.append(current_list)

print(lists)
print()

for j in range(len(lists)):
    temp_sum = 0
    for k in range(len(lists[j])):
        temp_sum += int(lists[j][k])
        if temp_sum > sum:
            sum = temp_sum
            sum_list = lists[j]

print("highest sum :",sum)
print()
print("list with the highest sum :",sum_list)

In [ ]:
#Task 2(Class)
N = int(input())
list1 = []
n_list = []
sum_list = []
idx = 0

for i in range(N):
  str = input()
  list1 = str.split()
  for j in range(len(list1)):
    list1[j] = int(list1[j])
  n_list.append(list1)
  sum = 0
  for k in range(len(list1)):
    sum += list1[k]
  sum_list.append(sum)

for m in range(len(n_list)):
  temp_sum = 0
  for n in range(len(sum_list)):
    if temp_sum < sum_list[n]:
      temp_sum = sum_list[n]
      idx = n

print()
print(sum_list[idx])
print(n_list[idx])

4
1 2 3
4 5 6
10 11 12
7 8 9

33
[10, 11, 12]

In [ ]:
# Task 3
# list1 = [2,3,6]
# list2 = [3,4,5]
# m_list = []

# for i in range(len(list1)):
#   for j in range(len(list2)):
#     n_list += [list1[i]*list2[j]]

# print(m_list)

# list1 = []
# m_list = []
# sum_list = []

# for i in range(2):
#   str = input()
#   list1 = str.split()
#   for j in range(len(list1)):
#     list1[j] = int(list1[j])
#   m_list.append(list1)
# print(m_list)

# for j in range(len(m_list)):
#   for k in range(len(m_list[j]-1)):
#     sum_list += [m_list[j][k]*m_list[j+1][k]]
# print(sum_list)

list1 = []
m_list = []
sum_list = []

str = input("enter first list : ")
list1 = str.split()
for j in range(len(list1)):
  list1[j] = int(list1[j])
m_list.append(list1)
print(m_list)

str2 = input("enter second list : ")
list1 = str2.split()
for j in range(len(list1)):
  list1[j] = int(list1[j])
m_list.append(list1)
print(m_list)

1 2 3
4 5 6
[[1, 2, 3], [4, 5, 6]]

In [ ]:
#Task 3

inpStr1 = input() + " "
inpStr2 = input() + " "

list1 = [int(value) for value in inpStr1.split()]
list2 = [int(value) for value in inpStr2.split()]

resultList = [k * l for k in list1 for l in list2]

print(resultList)

In [ ]:
#Task 4
list1 = []

while True:
    user = input("enter the list values : ")
    if user == "STOP":
        break
    else:
        list1.append(user)

for i in list1:
    list1 = [int(val) for val in i.split()]

    N = len(list1)

    for j in range(len(list1)-1):
        if (abs(int(list1[j]) - int(list1[j+1]))) not in range(1,N):
            print("not UB Jumper")
            break
    else:
        print("UB Jumper")

In [ ]:
#Task 5(Class)
#make 4 lists --> sort them(selection sort) --> add in a new string

#selection sort
#given = [42, 50, 33, 45]
given = ['r','a','c','u']
for i in range(len(given) -1):
  min1 = i
  for j in range(i+1, len(given)):
    if given[j] < given[min1]:
                 min1 = j
  given[i], given[min1] = given[min1], given[i]
print(given)

['a', 'c', 'r', 'u']

In [ ]:
#Task 5
input_str = input("type any word")
chars = list(input_str)
new_str = []

# Process lowercase letters
for char in sorted(chars):
    if char.islower():
        new_str.append(char)

# Process uppercase letters
for char in sorted(chars):
    if char.isupper():
        new_str.append(char)

# Process odd digits
for char in sorted(chars):
    if char.isdigit() and int(char) % 2 != 0:
        new_str.append(char)

# Process even digits
for char in sorted(chars):
    if char.isdigit() and int(char) % 2 == 0:
        new_str.append(char)

# Concatenate the results
result = ''.join(new_str)
print(result)

In [ ]:
#Task 6(Class)
#discussed the context

In [ ]:
#Task 6
n = int(input())  # Number of students
k = int(input())  # Minimum number of times each team should participate in the world championship
lst = []  # List to store the participation history of each student

# Input the participation history for each student
for i in range(n):
    np = int(input())
    lst.append(np)

student = 0  # Variable to count the eligible students

# Count the number of students who can participate in a team
for i in lst:
    if i + k <= 5:
        student += 1

team = student // 3  # Calculate the maximum number of teams that can be formed

print(team)

DICTIONARY & TUPLE

In [ ]:
#Task 1(Class)
d1 = {'a':100,'b':100,'c':200,'d':300}
d2 = {'a':300,'b':200,'d':400,'e':200}

for k, v in d2.items():
  if k not in d1.keys():
    d1[k] = v
  else:
    d1[k] = d1[k] + v
print(d1)

tuple1 = []
for k in d1.values():
  tuple1 += [k]
tuple1 = tuple(sorted(tuple1))
print(tuple1)

{'a': 400, 'b': 300, 'c': 200, 'd': 700, 'e': 200}
(200, 200, 300, 400, 700)

In [ ]:
#Task 1
d1 = {'a':100,'b':100,'c':200,'d':300}
d2 = {'a':300,'b':200,'d':400,'e':200}

for k, v in d2.items():
  if k not in d1.keys():
    d1[k] = v
  else:
    d1[k] = d1[k] + v
print(d1)

list1 = list(d1.values())
s_list = []

for i in list1:
  if i not in s_list:
    s_list += [i]
  else:
    pass

for i in range(len(s_list)):
  min_x = i
  for j in range(i+1, len(s_list)):
    if s_list[j] < s_list[min_x]:
      min_x = j
  s_list[i], s_list[min_x] = s_list[min_x], s_list[i]

s_tuple = tuple(s_list)
print("Values :",s_tuple)

In [ ]:
#Task 2

list1 = []
dict1={}
while True:
  num = input("Enter number: ")
  if num =="STOP":
    break
  else:
    a = int(num)
    list1+=[a]

for item in list1:
  if item not in dict1:
    dict1[item]=1
  else:
    dict1[item]+=1

for i in dict1.keys():
  print(f'{i} - {dict1[i]} times')

In [ ]:
#Task 3

dict1 = {}
dict2 = {}
num = int(input("Enter the number of elements in the dictionary: "))
for i in range(num):
  k = input("Enter key: ")
  v = input("Enter value: ")
  dict1[k]=v

for key,value in dict1.items():
  if value not in dict2:
    dict2[value] = []
    dict2[value].append(key)
  else:
    dict2[value].append(key)
print(dict2)

In [ ]:
#Task 4

dict1={}
temp = ""
str_input = input()
for i in str_input:
  if ord(i)>64 and ord(i)<91:
    temp+= chr(ord(i)+32)
  elif i!= " ":
    temp+= i
for j in temp:
  if j not in dict1:
    dict1[j]=1
  else:
    dict1[j]+=1

print(dict1)

In [ ]:
#Task 5

dict1 = {}
dict2 = {}
inp1 = input("Enter the first string: ")
inp2 = input("Enter the second string: ")

for i in inp1:
  if i not in dict1:
    dict1[i] = 1
  else:
    dict1[i]+=1
for j in inp2:
  if j not in dict2:
    dict2[j] = 1
  else:
    dict2[j]+=1

if dict1==dict2:
  print("Those strings are anagrams")
else:
  print("Those strings are not anagrams")

In [1]:
#Task 6

dict1 = {1:".,?!:",2:"ABC",3:"DEF",4:"GHI",5:"JKL",6:"MNO",
         7:"PQRS",8:"TUV",9:"WXYZ",0:" "}

user_input = input("Enter message: ")
same_case = ""
for i in user_input:
  if ord(i)>96 and ord(i)<123:
    same_case+= chr(ord(i)-32)
  else:
    same_case+=i
display = ""
for j in same_case:
  for key,value in dict1.items():
    for k in range(len(value)):
      if j==value[k]:
        display += (k+1)*str(key)

print(display)

Enter message: H
44